services:
  app:
    container_name: go-clean-arh-webapi-app
    image: go-clean-arh-webapi-app
    build:
      context: ..
      dockerfile: .devcontainer/app/Dockerfile
    ports:
      - 8080:8080
    tty: true
    environment:
      - PORT=8080
    volumes:
      - ../:/app
    working_dir: /app
    env_file:
      - ../app/.env
  db:
    container_name: go-clean-arh-webapi-db
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go-clean-arh-webapi
      - TZ=Asia/Tokyo
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql